name: Package exe with PyInstaller - Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyInstaller
      run: python -m pip install --upgrade pip pyinstaller
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Fix bug typing
      run: pip uninstall typing
    - name: Build
      run: ./build.bat
    - uses: actions/upload-artifact@v3
      with:
        name: Network_Track
        path: ./dist/Network_Track.exe